---
  - name: cresting user with Ansible
    hosts: all
    vars_files:
        - users.yml
    tasks:
    - name: creating devops user shivag
      ansible.builtin.user:
        name: "{{ item.name }}"
        group: "{{ item.group }}"
        state: present
        remove: false
      with_items: "{{ users }}"
    - name: Create SSH folders
      file:
        path: /home/{{item.name }}/.ssh
        owner: "{{ item.name }}"
        state: directory
      with_items: "{{ users }}"
    - name: create Authorized keys files
      file:
        path: "/home/{{ item.name }}/.ssh/authorized_keys"
        state: touch
        owner: "{{ item.name }}"
      with_items: "{{ users }}"
    - name: Manage ssh key
      authorized_key:
        user: "{{ item.name }}"
        key: "{{ lookup('file', 'pub_key') }}"
        state: present
      with_items: "{{ users }}"
